// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.lc4ever.framework.domain.cdm;

import net.lc4ever.framework.domain.cdm.Domain;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Domain_Roo_Configurable {
    
    declare @type: Domain: @Configurable;
    
}
