// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.lc4ever.framework.domain.cdm;

import java.io.Serializable;
import net.lc4ever.framework.domain.cdm.Domain;

privileged aspect Domain_Roo_Serializable {
    
    declare parents: Domain implements Serializable;
    
    private static final long Domain.serialVersionUID = 1L;
    
}
