// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.lc4ever.framework.domain.cdm;

import net.lc4ever.framework.domain.cdm.DomainIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DomainIntegrationTest_Roo_Configurable {
    
    declare @type: DomainIntegrationTest: @Configurable;
    
}
